name: The Works Enterprises
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2513
title: A Hub for the Creative Arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363435'
    - '#eb353d'
    - '#fefefe'
    - '#808080'
    - '#f7a9ad'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
